### ISSUE TITLE
The getter 'themeData' was called on null

### ISSUE THREAD

**Issue by riskiadi** [neumorphic/neumorphic.flutter#10]
The getter 'themeData' was called on null.
Receiver: null
Tried calling: themeData

> class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
//    return MaterialApp(title: "Kurmaku", home: LoginScreen());
  return NeuApp(
    theme: NeuThemeData(
      brightness: Brightness.dark,
      primaryColor: Colors.blueGrey,
      curveType: CurveType.concave,
      lightSource: LightSource.topLeft, // Not implemented yet
    ),
    home: Scaffold(
      appBar: NeuAppBar(
        title: const Text('NeumorphicApp Theme'),
      ),
    ),
  );
  }
}

**Comment by jackylope** [comment]
You must set a darkTheme in your NeuApp.

**Comment by yulkin2002** [comment]
> 
> 
> You must set a darkTheme in your NeuApp.

could you please elaborate on how to do that since we are assigning NeuThemeData to a theme parameter?

**Comment by NiklasLehnfeld** [comment]
I hope you already fixed your issue. If not, try this out:

```
class _MyAppState extends State {
  @override
  Widget build(BuildContext context) {
// return MaterialApp(title: "Kurmaku", home: LoginScreen());
    return NeuApp(
      darkTheme: NeuThemeData(
        appBarTheme: AppBarTheme()
      ),
      theme: NeuThemeData(
        appBarTheme: AppBarTheme(),
        brightness: Brightness.dark,
        primaryColor: Colors.blueGrey,
        curveType: CurveType.concave,
        lightSource: LightSource.topLeft, // Not implemented yet
      ),
      home: Scaffold(
        appBar: NeuAppBar(
          title: const Text('NeumorphicApp Theme'),
        ),
      ),
    );
  }
}

```
