### ISSUE TITLE
lost builder

### ISSUE THREAD

**Issue by wengxianxun** [neumorphic/neumorphic.flutter#16]
return MaterialApp(
      debugShowCheckedModeBanner: false,
      builder: DialogContext().builder,
      title: "my tete",

builder arg is lost

**Comment by predatorx7** [comment]
NeuApp in latest neumorphic does have a builder field. [Check API documentation for NeuApp.builder](https://pub.dev/documentation/neumorphic/latest/neumorphic/NeuApp/builder.html).

**Comment by predatorx7** [comment]
Closing this issue because of no response from OP. You may reopen the issue if there is a problem.
