### ISSUE TITLE
Changing the color of teh NeuButton or the NeuSwitch.

### ISSUE THREAD

**Issue by pratikbaid3** [neumorphic/neumorphic.flutter#5]
The property of decoration does not exist for NeuButton or the NeuSwitch like it does for the NeuCard.

**Comment by predatorx7** [comment]
I've added properties to change color, radius, bevel in NeuSwitch.
NeuButton didn't need a property for decoration for now. We'll concentrate on that in later releases.

Closing this issue as it's resolved.
