### ISSUE TITLE
Neumorphic 0.2.0 not working at all

### ISSUE THREAD

**Issue by m8dotpie** [neumorphic/neumorphic.flutter#6]
Steps to reproduce:
- using flutter master channel
- Import neumorphic library to sample flutter project.
- Add simple NeuCard with any children.

```
Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/neumorphic-0.2.0/lib/src/neumorphic/theme_data.dart:446:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const NeuThemeData.raw({
```

**Comment by m8dotpie** [comment]
Flutter channel stable working well, but may be useful to take note about possible changes if it is not something broken in master

**Comment by SergeShkurko** [comment]
Видимо в мастер ветке флаттера при поменяли, сталкивался с этим уже раньше, как будет стабильная а подходе поправлю :)

**Comment by m8dotpie** [comment]
> Видимо в мастер ветке флаттера при поменяли, сталкивался с этим уже раньше, как будет стабильная а подходе поправлю :)

Стоит учесть, что вообще из всех веток, плагин работает только на стабильной, все остальные уже внедрили изменения

**Comment by m8dotpie** [comment]
Проблема возникла из-за желания собрать web приложение с использованием этого плагина, но возможность build web есть везде кроме стабильной ветки

**Comment by SergeShkurko** [comment]
Когда экспериментировал на вэбе выглядело неестественно из-за плохой отрисовки теней, впрочем посмотрю как выкроится свободная минутка
