### ISSUE TITLE
cant build with version 0.2.0, version 0.1.2 is working fine

### ISSUE THREAD

**Issue by athul-ain** [neumorphic/neumorphic.flutter#8]
Compiler message:
/C:/Users/athul/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/neumorphic-0.2.0/lib/src/neumorphic/theme_data.dart:446:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const NeuThemeData.raw({
        ^^^

Compiler message:
/C:/Users/athul/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/neumorphic-0.2.0/lib/src/neumorphic/theme_data.dart:446:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const NeuThemeData.raw({
        ^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\NXT\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\NXT\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by SergeShkurko** [comment]
flatter chunnel is stable?

**Comment by SergeShkurko** [comment]
same issue #6
